package net.zoogle.enchiridion.client.anim;

public enum BookAnimState {
    ARRIVING,
    CLOSED,
    CLOSING,
    OPENING,
    IDLE_OPEN,
    IDLE_FRONT,
    IDLE_BACK,
    IDLE_SKILLTREE,
    FLIPPING_FRONT,
    FLIPPING_FRONT_TO_ORIGIN,
    FLIPPING_BACK,
    FLIPPING_BACK_TO_ORIGIN,
    FLIPPING_NEXT,
    FLIPPING_PREV,
    FLIPPING_NEXT_SKILLTREE,
    FLIPPING_PREV_SKILLTREE,
    RIFFLING_NEXT,
    RIFFLING_PREV,
    RIFFLING_NEXT_SKILLTREE,
    RIFFLING_PREV_SKILLTREE
}
